name: Overworld Bug Report
description: File a bug report for the Iris Dimensions Overworld
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please give a text description of the issue
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What should happen?
      description: Please give a text description of what you think the problem is
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: dropdown
    id: mcversion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.16.5
        - 1.17
    validations:
      required: true
  - type: dropdown
    id: irisversion
    attributes:
      label: Iris Version
      description: What version of Iris are you running?
      options:
        - 1.3.9
        - 1.3.10-FINAL
        - 1.3.11-FINAL
        - 1.4.1
        - 1.4.2
        - 1.4.3
        - 1.4.4
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: There is an error connected to this issue
      multiple: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: checksum
    attributes:
      label: Checklist
      description: Please ensure you have done each of the steps here:
      options:
        - label: I am using an unmodified version of the overworld (If you modified the overworld and see the issue, contact [support](discord.gg/volmit)).
          required: true
        - label: I am using the latest version of the overworld **OR** I have made sure this issue was not already resolved on the latest version.
